### ISSUE TITLE
Load balancing does not work properly with long lasting queries (503 error)

### ISSUE THREAD

**Issue by pkrp** [icatproject/icat.server#150]
With basic configuration provided with documentation (http://icatproject.org/installation/apache-front-end/) load balancing works well only with simple queries.

JPQL query causing error (ISIS database, takes ~40 seconds):

```
SELECT datafile FROM Datafile datafile WHERE (datafile.dataset.id = '24078846') ORDER BY datafile.name
```

Error:

```
Exception in thread "main" com.sun.xml.internal.ws.client.ClientTransportException: The server sent HTTP status code 503: Service Temporarily Unavailable
    at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.checkStatusCode(Unknown Source)
    at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.createResponsePacket(Unknown Source)
    at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.process(Unknown Source)
    at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest(Unknown Source)
    at com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest(Unknown Source)
    at com.sun.xml.internal.ws.api.pipe.Fiber.__doRun(Unknown Source)
    at com.sun.xml.internal.ws.api.pipe.Fiber._doRun(Unknown Source)
    at com.sun.xml.internal.ws.api.pipe.Fiber.doRun(Unknown Source)
    at com.sun.xml.internal.ws.api.pipe.Fiber.runSync(Unknown Source)
    at com.sun.xml.internal.ws.client.Stub.process(Unknown Source)
    at com.sun.xml.internal.ws.client.sei.SEIStub.doProcess(Unknown Source)
    at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(Unknown Source)
    at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(Unknown Source)
    at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(Unknown Source)
    at com.sun.proxy.$Proxy36.search(Unknown Source)
```

Httpd log:

```
[Tue Aug 18 11:31:39 2015] [error] (70014)End of file found: ajp_ilink_receive() can't receive header
[Tue Aug 18 11:31:39 2015] [error] ajp_read_header: ajp_ilink_receive failed
[Tue Aug 18 11:31:39 2015] [error] (120006)APR does not understand this error code: proxy: dialog to (null) (vm165.nubes.stfc.ac.uk) failed
```

**Comment by fisherab** [comment]
This is being removed from 4.7 to avoid delaying it further

**Comment by fisherab** [comment]
This was probably a misconfiguration of Apache. https://icatproject.org/installation/apache-front-end/ now explains how to specify timeouts to override the one minute default.
