### ISSUE TITLE
searching for "Study INCLUDE StudyInvestigation" raises java.lang.NullPointerException

### ISSUE THREAD

**Issue by RKrahl** [icatproject/icat.server#155]
I got a `Study` in the ICAT, related to an `Investigation` via `StudyInvestigation`.  I get an internal error from the server when I search for "Study INCLUDE StudyInvestigation":

```python
>>> client.search("Study INCLUDE StudyInvestigation")
ERROR:suds.client:<suds.sax.document.Document instance at 0x1842b00>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/icat/client.py", line 472, in search
    raise translateError(e)
icat.exception.ICATInternalError: java.lang.NullPointerException
```

This happens with icat.server 4.5.1 and with the current 4.6.0 snapshot.  See the [icat.log](https://github.com/icatproject/icat.server/files/41610/icat.log.txt) for a full error trace.

**Comment by RKrahl** [comment]
Note that searching the other way round works:

```python
>>> client.search("Investigation INCLUDE StudyInvestigation, Study [name='10100601-ST']")
[(investigation){
   createId = "root"
   createTime = 2015-11-23 13:51:37+01:00
   id = 4
   modId = "root"
   modTime = 2015-11-23 13:51:37+01:00
   endDate = 2010-10-12 17:00:00+02:00
   name = "10100601-ST"
   startDate = 2010-09-30 12:27:24+02:00
   studyInvestigations[] = 
      (studyInvestigation){
         createId = "root"
         createTime = 2015-11-23 14:49:03+01:00
         id = 6
         modId = "root"
         modTime = 2015-11-23 14:49:03+01:00
         study = 
            (study){
               createId = "root"
               createTime = 2015-11-23 14:49:03+01:00
               id = 4
               modId = "root"
               modTime = 2015-11-23 14:49:03+01:00
               name = "12-008"
               startDate = 2012-07-09 08:00:00+02:00
               status = "COMPLETE"
            }
      },
   title = "Ni-Mn-Ga flat cone"
   visitId = "1.1-N"
 }]
```
