### ISSUE TITLE
update() throws an internal error

### ISSUE THREAD

**Issue by RKrahl** [icatproject/icat.server#163]
With the new release 4.6 of icat.server I get an internal error from the update() call:
```python
>>> # Create a dataset
... 
>>> dataset = client.new("dataset")
>>> dataset.name = "test dataset"
>>> dataset.complete = False
>>> dataset.investigation = investigation
>>> dataset.type = datasetType
>>> dataset.create()
>>> # Modify an attribute and update it
... 
>>> dataset.complete = True
>>> dataset.update()
ERROR:suds.client:<suds.sax.document.Document instance at 0x7ff23e4727a0>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/net/home/jsi/ICAT/python-icat/build/lib/icat/entity.py", line 412, in update
    self.client.update(self)
  File "/net/home/jsi/ICAT/python-icat/build/lib/icat/client.py", line 478, in update
    raise translateError(e)
icat.exception.ICATInternalError: IllegalStateExceptionTransaction is not active in the current thread.
```

I use openjdk 1.8.0.72.  See the relevant of the [server.log](https://github.com/icatproject/icat.server/files/142902/server.log.txt) with the Java traceback.

**Comment by RKrahl** [comment]
As the code around the offending line Dataset.java:213 suggests, the error does not occur if startDate and endDate in the dataset are set:
```python
>>> dataset = client.new("dataset")
>>> dataset.name = "test dataset 2"
>>> dataset.complete = False
>>> dataset.startDate = datetime.datetime.now(UtcTimezone())
>>> dataset.endDate = datetime.datetime.now(UtcTimezone())
>>> dataset.investigation = investigation
>>> dataset.type = datasetType
>>> dataset.create()
>>> dataset.complete = True
>>> dataset.update()
```

**Comment by fisherab** [comment]
Yes - I just bumped into the problem myself. I am surprised it got past my tests. A 4.6.1 will be along ASAP.
