### ISSUE TITLE
Bad argument should not throw Internal Exception

### ISSUE THREAD

**Issue by fisherab** [icatproject/icat.server#181]
The following attempt to add a new datafile to an existing dataset:

    datafile = [{"name" : "df3", "location" : "loc3", "dataset" : {"id" : newdsid}}]
    entity = {"Datafile" : datafile}
    self.session.write(entity)
resulted in the stack trace:

Traceback (most recent call last):
File "test.py", line 173, in test12AddFile
self.session.write(entity)
File "/usr/local/lib/python2.7/dist-packages/icat.py", line 332, in write
return self.icat._write(self.sessionId, entities)
File "/usr/local/lib/python2.7/dist-packages/icat.py", line 143, in _write
self._check(r)
File "/usr/local/lib/python2.7/dist-packages/icat.py", line 64, in _check
raise IcatException(json["code"], json["message"])
IcatException: INTERNAL: class javax.ejb.EJBException Stateless SessionBean method returned without completing transaction

**Comment by fisherab** [comment]
This is copied from issue icatproject/icat.client#9
